# Generated by Django 5.1.5 on 2025-02-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_activitie_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activitie',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
