# Generated by Django 5.1.5 on 2025-02-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_delete_activitie_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackedactivitie',
            table='Coach_details',
        ),
    ]
