# Generated by Django 5.1.5 on 2025-02-22 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_trackedactivitie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackedactivitie',
            table=None,
        ),
    ]
