# Generated by Django 5.1.5 on 2025-02-24 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_trackedactivitie_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedactivitie',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
